import puppeteer from 'puppeteer';
import fetch from 'node-fetch';
import { generateTestAction } from './actionUtils/utils.js';

const getTestJson = async () => {
  const data = await fetch(
    'https://danielad37.wixsite.com/oozy-test/_functions/oozy_the_king',
  )
    .then((response) => response.json())
    .then((data) => data);
  // return data;
  return {
    height: 1001,
    width: 839,
    tests: [
      {
        element: 'div',
        action: 'mouseover',
        dataHook: 'app',
        x: 715,
        y: 648,
        value:
          "DRIVE-HAPPIER\nemail *\nPassword *\nLOGIN\nDON'T HAVE AN ACCOUNT ?\nLOGIN WITH FACEBOOK",
        time: 1626641683084,
        pageUrl: 'http://localhost:3002/login',
      },
      {
        element: 'div',
        action: 'mouseover',
        dataHook: 'app',
        x: 631,
        y: 547,
        value:
          "DRIVE-HAPPIER\nemail *\nPassword *\nLOGIN\nDON'T HAVE AN ACCOUNT ?\nLOGIN WITH FACEBOOK",
        time: 1626641683128,
        pageUrl: 'http://localhost:3002/login',
      },
      {
        element: 'input',
        action: 'mouseover',
        dataHook: 'login-form-password-input',
        x: 581,
        y: 511,
        value: 'diveTech@diveTech.com',
        time: 1626641683150,
        pageUrl: 'http://localhost:3002/login',
      },
      {
        element: 'div',
        action: 'mouseover',
        dataHook: 'app',
        x: 504,
        y: 479,
        value:
          "DRIVE-HAPPIER\nemail *\nPassword *\nLOGIN\nDON'T HAVE AN ACCOUNT ?\nLOGIN WITH FACEBOOK",
        time: 1626641683207,
        pageUrl: 'http://localhost:3002/login',
      },
      {
        element: 'div',
        action: 'mouseover',
        dataHook: 'app',
        x: 452,
        y: 462,
        value:
          "DRIVE-HAPPIER\nemail *\nPassword *\nLOGIN\nDON'T HAVE AN ACCOUNT ?\nLOGIN WITH FACEBOOK",
        time: 1626641683319,
        pageUrl: 'http://localhost:3002/login',
      },
      {
        element: 'input',
        action: 'mouseover',
        dataHook: 'login-form-input',
        x: 382,
        y: 368,
        value: 'diveTech@diveTech.com',
        time: 1626641683469,
        pageUrl: 'http://localhost:3002/login',
      },
      {
        element: 'div',
        action: 'mouseover',
        dataHook: 'app',
        x: 383,
        y: 337,
        value:
          "DRIVE-HAPPIER\nemail *\nPassword *\nLOGIN\nDON'T HAVE AN ACCOUNT ?\nLOGIN WITH FACEBOOK",
        time: 1626641683545,
        pageUrl: 'http://localhost:3002/login',
      },
      {
        element: 'div',
        action: 'mousedown',
        dataHook: 'app',
        x: 384,
        y: 331,
        value:
          "DRIVE-HAPPIER\nemail *\nPassword *\nLOGIN\nDON'T HAVE AN ACCOUNT ?\nLOGIN WITH FACEBOOK",
        time: 1626641683625,
        pageUrl: 'http://localhost:3002/login',
      },
      {
        element: 'div',
        action: 'mouseup',
        dataHook: 'app',
        x: 384,
        y: 331,
        value:
          "DRIVE-HAPPIER\nemail *\nPassword *\nLOGIN\nDON'T HAVE AN ACCOUNT ?\nLOGIN WITH FACEBOOK",
        time: 1626641683701,
        pageUrl: 'http://localhost:3002/login',
      },
      {
        element: 'div',
        action: 'click',
        dataHook: 'app',
        x: 384,
        y: 331,
        value:
          "DRIVE-HAPPIER\nemail *\nPassword *\nLOGIN\nDON'T HAVE AN ACCOUNT ?\nLOGIN WITH FACEBOOK",
        time: 1626641683702,
        pageUrl: 'http://localhost:3002/login',
      },
      {
        element: 'input',
        action: 'mouseover',
        dataHook: 'login-form-input',
        x: 380,
        y: 342,
        value: 'diveTech@diveTech.com',
        time: 1626641683859,
        pageUrl: 'http://localhost:3002/login',
      },
      {
        element: 'input',
        action: 'mousedown',
        dataHook: 'login-form-input',
        x: 375,
        y: 353,
        value: 'diveTech@diveTech.com',
        time: 1626641683949,
        pageUrl: 'http://localhost:3002/login',
      },
      {
        element: 'input',
        action: 'mouseup',
        dataHook: 'login-form-input',
        x: 375,
        y: 353,
        value: 'diveTech@diveTech.com',
        time: 1626641684041,
        pageUrl: 'http://localhost:3002/login',
      },
      {
        element: 'input',
        action: 'click',
        dataHook: 'login-form-input',
        x: 375,
        y: 353,
        value: 'diveTech@diveTech.com',
        time: 1626641684042,
        pageUrl: 'http://localhost:3002/login',
      },
      {
        element: 'input',
        action: 'mousedown',
        dataHook: 'login-form-input',
        x: 388,
        y: 342,
        value: 'oozy13@test.com',
        time: 1626641690947,
        pageUrl: 'http://localhost:3002/login',
      },
      {
        element: 'input',
        action: 'mouseup',
        dataHook: 'login-form-input',
        x: 388,
        y: 342,
        value: 'oozy13@test.com',
        time: 1626641691014,
        pageUrl: 'http://localhost:3002/login',
      },
      {
        element: 'input',
        action: 'click',
        dataHook: 'login-form-input',
        x: 388,
        y: 342,
        value: 'oozy13@test.com',
        time: 1626641691015,
        pageUrl: 'http://localhost:3002/login',
      },
      {
        element: 'div',
        action: 'mouseover',
        dataHook: 'app',
        x: 624,
        y: 443,
        value:
          "DRIVE-HAPPIER\nemail *\nPassword *\nLOGIN\nDON'T HAVE AN ACCOUNT ?\nLOGIN WITH FACEBOOK",
        time: 1626641691839,
        pageUrl: 'http://localhost:3002/login',
      },
      {
        element: 'div',
        action: 'mousedown',
        dataHook: 'app',
        x: 624,
        y: 443,
        value:
          "DRIVE-HAPPIER\nemail *\nPassword *\nLOGIN\nDON'T HAVE AN ACCOUNT ?\nLOGIN WITH FACEBOOK",
        time: 1626641692187,
        pageUrl: 'http://localhost:3002/login',
      },
      {
        element: 'input',
        action: 'change',
        dataHook: 'login-form-input',
        x: 0,
        y: 0,
        value: 'oozy13@test.com',
        time: 1626641692188,
        pageUrl: 'http://localhost:3002/login',
      },
      {
        element: 'div',
        action: 'mouseup',
        dataHook: 'app',
        x: 624,
        y: 443,
        value:
          "DRIVE-HAPPIER\nemail *\nPassword *\nLOGIN\nDON'T HAVE AN ACCOUNT ?\nLOGIN WITH FACEBOOK",
        time: 1626641692262,
        pageUrl: 'http://localhost:3002/login',
      },
      {
        element: 'div',
        action: 'click',
        dataHook: 'app',
        x: 624,
        y: 443,
        value:
          "DRIVE-HAPPIER\nemail *\nPassword *\nLOGIN\nDON'T HAVE AN ACCOUNT ?\nLOGIN WITH FACEBOOK",
        time: 1626641692263,
        pageUrl: 'http://localhost:3002/login',
      },
      {
        element: 'div',
        action: 'mouseover',
        dataHook: 'app',
        x: 433,
        y: 465,
        value:
          "DRIVE-HAPPIER\nemail *\nPassword *\nLOGIN\nDON'T HAVE AN ACCOUNT ?\nLOGIN WITH FACEBOOK",
        time: 1626641692681,
        pageUrl: 'http://localhost:3002/login',
      },
      {
        element: 'input',
        action: 'mouseover',
        dataHook: 'login-form-password-input',
        x: 397,
        y: 480,
        value: 'diveTech@diveTech.com',
        time: 1626641692770,
        pageUrl: 'http://localhost:3002/login',
      },
      {
        element: 'input',
        action: 'mousedown',
        dataHook: 'login-form-password-input',
        x: 385,
        y: 485,
        value: 'diveTech@diveTech.com',
        time: 1626641692858,
        pageUrl: 'http://localhost:3002/login',
      },
      {
        element: 'input',
        action: 'mouseup',
        dataHook: 'login-form-password-input',
        x: 385,
        y: 485,
        value: 'diveTech@diveTech.com',
        time: 1626641692949,
        pageUrl: 'http://localhost:3002/login',
      },
      {
        element: 'input',
        action: 'click',
        dataHook: 'login-form-password-input',
        x: 385,
        y: 485,
        value: 'diveTech@diveTech.com',
        time: 1626641692950,
        pageUrl: 'http://localhost:3002/login',
      },
      {
        element: 'div',
        action: 'mouseover',
        dataHook: 'app',
        x: 379,
        y: 514,
        value:
          "DRIVE-HAPPIER\nemail *\nPassword *\nLOGIN\nDON'T HAVE AN ACCOUNT ?\nLOGIN WITH FACEBOOK",
        time: 1626641695379,
        pageUrl: 'http://localhost:3002/login',
      },
      {
        element: 'div',
        action: 'mousedown',
        dataHook: 'app',
        x: 359,
        y: 562,
        value:
          "DRIVE-HAPPIER\nemail *\nPassword *\nLOGIN\nDON'T HAVE AN ACCOUNT ?\nLOGIN WITH FACEBOOK",
        time: 1626641695627,
        pageUrl: 'http://localhost:3002/login',
      },
      {
        element: 'input',
        action: 'change',
        dataHook: 'login-form-password-input',
        x: 0,
        y: 0,
        value: '123456',
        time: 1626641695628,
        pageUrl: 'http://localhost:3002/login',
      },
      {
        element: 'div',
        action: 'mouseup',
        dataHook: 'app',
        x: 358,
        y: 563,
        value:
          "DRIVE-HAPPIER\nemail *\nPassword *\nLOGIN\nDON'T HAVE AN ACCOUNT ?\nLOGIN WITH FACEBOOK",
        time: 1626641695693,
        pageUrl: 'http://localhost:3002/login',
      },
      {
        element: 'div',
        action: 'click',
        dataHook: 'app',
        x: 358,
        y: 563,
        value:
          "DRIVE-HAPPIER\nemail *\nPassword *\nLOGIN\nDON'T HAVE AN ACCOUNT ?\nLOGIN WITH FACEBOOK",
        time: 1626641695694,
        pageUrl: 'http://localhost:3002/login',
      },
      {
        element: 'button',
        action: 'mouseover',
        dataHook: 'Login-form-submit-btn',
        x: 361,
        y: 605,
        value: 'LOGIN',
        time: 1626641695988,
        pageUrl: 'http://localhost:3002/login',
      },
      {
        element: 'button',
        action: 'mouseover',
        dataHook: 'Login-form-submit-btn',
        x: 363,
        y: 611,
        value: 'LOGIN',
        time: 1626641696019,
        pageUrl: 'http://localhost:3002/login',
      },
      {
        element: 'button',
        action: 'mousedown',
        dataHook: 'Login-form-submit-btn',
        x: 366,
        y: 612,
        value: 'LOGIN',
        time: 1626641696227,
        pageUrl: 'http://localhost:3002/login',
      },
      {
        element: 'button',
        action: 'mouseup',
        dataHook: 'Login-form-submit-btn',
        x: 366,
        y: 612,
        value: 'LOGIN',
        time: 1626641696304,
        pageUrl: 'http://localhost:3002/login',
      },
      {
        element: 'button',
        action: 'click',
        dataHook: 'Login-form-submit-btn',
        x: 366,
        y: 612,
        value: 'LOGIN',
        time: 1626641696306,
        pageUrl: 'http://localhost:3002/login',
      },
      {
        element: 'div',
        action: 'mouseover',
        dataHook: 'app',
        x: 366,
        y: 612,
        value:
          "DRIVE-HAPPIER\nemail *\nPassword *\nLOADING . . .\nDON'T HAVE AN ACCOUNT ?\nLOGIN WITH FACEBOOK",
        time: 1626641696339,
        pageUrl: 'http://localhost:3002/login',
      },
      {
        element: 'div',
        action: 'mouseover',
        dataHook: 'cars-board',
        x: 366,
        y: 612,
        value:
          'ADD NEW CAR\n\nYears Range\n\n1990\n2020\n\nPrice Range\n\n200\n90000\nCar Brand\nChoose\nAll Brands\nSort By\nChoose\nPrices High To Low\nPrices Low To High\nNewest Year\nFILTER\nDISPLAY ALL',
        time: 1626641696523,
        pageUrl: 'http://localhost:3002/cars-board',
      },
      {
        element: 'div',
        action: 'mouseover',
        dataHook: 'car-card',
        x: 366,
        y: 612,
        value: 'Mazda Model 323\n\nModel Year 2010\n\nPrice $3000',
        time: 1626641696944,
        pageUrl: 'http://localhost:3002/cars-board',
      },
      {
        element: 'div',
        action: 'mouseover',
        dataHook: 'cars-board',
        x: 366,
        y: 548,
        value:
          'ADD NEW CAR\n\nYears Range\n\n1990\n2020\n\nPrice Range\n\n200\n90000\nCar Brand\nChoose\nAll Brands\nMAZDA\nKIA\nHONDA\nMERCEDES\nTOYOTA\nLAMBORGHINI\nVOLLKSWAGEN\nPORSCHE\nAUDI\nSUBARU\nMITSUBISHI\nSATURN\nVOLKSWAGEN\nSort By\nChoose\nPrices High To Low\nPrices Low To High\nNewest Year\nFILTER\nDISPLAY ALL\nMazda Model 323\n\nModel Year 2010\n\nPrice $3000\n\nMazda Model 3\n\nModel Year 2010\n\nPrice $2222\n\nKia Model Rio\n\nModel Year 2014\n\nPrice $27000\n\nkia Model picanto\n\nModel Year 2012\n\nPrice $32000\n\nHonda Model Jazz\n\nModel Year 2017\n\nPrice $22000\n\nMercedes Model Benz\n\nModel Year 2019\n\nPrice $4500\n\nToyota Model Matrix\n\nModel Year 2015\n\nPrice $19000\n\nLamborghini Model Dorobantu\n\nModel Year 2020\n\nPrice $75000\n\nVollkswagen Model Beetle\n\nModel Year 1995\n\nPrice $999.9\n\nPorsche Model 928\n\nModel Year 1994\n\nPrice $2112.12\n\nAudi Model A5\n\nModel Year 2012\n\nPrice $2455.81\n\nSubaru Model Impreza\n\nModel Year 2006\n\nPrice $2437.81\n\nMitsubishi Model Montero\n\nModel Year 1996\n\nPrice $3217.31\n\nToyota Model Matrix\n\nModel Year 2005\n\nPrice $1238.19\n\nSaturn Model VUE\n\nModel Year 2006\n\nPrice $3042.96\n\nVolkswagen Model Passat\n\nModel Year 2008\n\nPrice $1731.98\n\nMitsubishi Model Montero\n\nModel Year 2002\n\nPrice $2814.46',
        time: 1626641697493,
        pageUrl: 'http://localhost:3002/cars-board',
      },
      {
        element: 'button',
        action: 'mouseover',
        dataHook: 'button-FILTER',
        x: 362,
        y: 463,
        value: 'FILTER',
        time: 1626641697517,
        pageUrl: 'http://localhost:3002/cars-board',
      },
      {
        element: 'form',
        action: 'mouseover',
        dataHook: 'submit-form',
        x: 358,
        y: 416,
        value:
          'Years Range\n\n1990\n2020\n\nPrice Range\n\n200\n90000\nCar Brand\nChoose\nAll Brands\nMAZDA\nKIA\nHONDA\nMERCEDES\nTOYOTA\nLAMBORGHINI\nVOLLKSWAGEN\nPORSCHE\nAUDI\nSUBARU\nMITSUBISHI\nSATURN\nVOLKSWAGEN\nSort By\nChoose\nPrices High To Low\nPrices Low To High\nNewest Year\nFILTER\nDISPLAY ALL',
        time: 1626641697527,
        pageUrl: 'http://localhost:3002/cars-board',
      },
      {
        element: 'form',
        action: 'mouseover',
        dataHook: 'submit-form',
        x: 351,
        y: 370,
        value:
          'Years Range\n\n1990\n2020\n\nPrice Range\n\n200\n90000\nCar Brand\nChoose\nAll Brands\nMAZDA\nKIA\nHONDA\nMERCEDES\nTOYOTA\nLAMBORGHINI\nVOLLKSWAGEN\nPORSCHE\nAUDI\nSUBARU\nMITSUBISHI\nSATURN\nVOLKSWAGEN\nSort By\nChoose\nPrices High To Low\nPrices Low To High\nNewest Year\nFILTER\nDISPLAY ALL',
        time: 1626641697541,
        pageUrl: 'http://localhost:3002/cars-board',
      },
      {
        element: 'span',
        action: 'mouseover',
        dataHook: 'slider-prices',
        x: 344,
        y: 331,
        value: '200\n90000',
        time: 1626641697550,
        pageUrl: 'http://localhost:3002/cars-board',
      },
      {
        element: 'form',
        action: 'mouseover',
        dataHook: 'submit-form',
        x: 335,
        y: 299,
        value:
          'Years Range\n\n1990\n2020\n\nPrice Range\n\n200\n90000\nCar Brand\nChoose\nAll Brands\nMAZDA\nKIA\nHONDA\nMERCEDES\nTOYOTA\nLAMBORGHINI\nVOLLKSWAGEN\nPORSCHE\nAUDI\nSUBARU\nMITSUBISHI\nSATURN\nVOLKSWAGEN\nSort By\nChoose\nPrices High To Low\nPrices Low To High\nNewest Year\nFILTER\nDISPLAY ALL',
        time: 1626641697562,
        pageUrl: 'http://localhost:3002/cars-board',
      },
      {
        element: 'span',
        action: 'mouseover',
        dataHook: 'slider-years',
        x: 306,
        y: 226,
        value: '1990\n2020',
        time: 1626641697586,
        pageUrl: 'http://localhost:3002/cars-board',
      },
      {
        element: 'form',
        action: 'mouseover',
        dataHook: 'submit-form',
        x: 288,
        y: 195,
        value:
          'Years Range\n\n1990\n2020\n\nPrice Range\n\n200\n90000\nCar Brand\nChoose\nAll Brands\nMAZDA\nKIA\nHONDA\nMERCEDES\nTOYOTA\nLAMBORGHINI\nVOLLKSWAGEN\nPORSCHE\nAUDI\nSUBARU\nMITSUBISHI\nSATURN\nVOLKSWAGEN\nSort By\nChoose\nPrices High To Low\nPrices Low To High\nNewest Year\nFILTER\nDISPLAY ALL',
        time: 1626641697594,
        pageUrl: 'http://localhost:3002/cars-board',
      },
      {
        element: 'p',
        action: 'mouseover',
        value: 'Years Range',
        time: 1626641697608,
        pageUrl: 'http://localhost:3002/cars-board',
      },
      {
        element: 'form',
        action: 'mouseover',
        dataHook: 'submit-form',
        x: 243,
        y: 154,
        value:
          'Years Range\n\n1990\n2020\n\nPrice Range\n\n200\n90000\nCar Brand\nChoose\nAll Brands\nMAZDA\nKIA\nHONDA\nMERCEDES\nTOYOTA\nLAMBORGHINI\nVOLLKSWAGEN\nPORSCHE\nAUDI\nSUBARU\nMITSUBISHI\nSATURN\nVOLKSWAGEN\nSort By\nChoose\nPrices High To Low\nPrices Low To High\nNewest Year\nFILTER\nDISPLAY ALL',
        time: 1626641697628,
        pageUrl: 'http://localhost:3002/cars-board',
      },
      {
        element: 'div',
        action: 'mouseover',
        dataHook: 'filter-bar',
        x: 186,
        y: 136,
        value:
          'Years Range\n\n1990\n2020\n\nPrice Range\n\n200\n90000\nCar Brand\nChoose\nAll Brands\nMAZDA\nKIA\nHONDA\nMERCEDES\nTOYOTA\nLAMBORGHINI\nVOLLKSWAGEN\nPORSCHE\nAUDI\nSUBARU\nMITSUBISHI\nSATURN\nVOLKSWAGEN\nSort By\nChoose\nPrices High To Low\nPrices Low To High\nNewest Year\nFILTER\nDISPLAY ALL',
        time: 1626641697922,
        pageUrl: 'http://localhost:3002/cars-board',
      },
      {
        element: 'div',
        action: 'mouseover',
        dataHook: 'cars-board',
        x: 185,
        y: 126,
        value:
          'ADD NEW CAR\n\nYears Range\n\n1990\n2020\n\nPrice Range\n\n200\n90000\nCar Brand\nChoose\nAll Brands\nMAZDA\nKIA\nHONDA\nMERCEDES\nTOYOTA\nLAMBORGHINI\nVOLLKSWAGEN\nPORSCHE\nAUDI\nSUBARU\nMITSUBISHI\nSATURN\nVOLKSWAGEN\nSort By\nChoose\nPrices High To Low\nPrices Low To High\nNewest Year\nFILTER\nDISPLAY ALL\nMazda Model 323\n\nModel Year 2010\n\nPrice $3000\n\nMazda Model 3\n\nModel Year 2010\n\nPrice $2222\n\nKia Model Rio\n\nModel Year 2014\n\nPrice $27000\n\nkia Model picanto\n\nModel Year 2012\n\nPrice $32000\n\nHonda Model Jazz\n\nModel Year 2017\n\nPrice $22000\n\nMercedes Model Benz\n\nModel Year 2019\n\nPrice $4500\n\nToyota Model Matrix\n\nModel Year 2015\n\nPrice $19000\n\nLamborghini Model Dorobantu\n\nModel Year 2020\n\nPrice $75000\n\nVollkswagen Model Beetle\n\nModel Year 1995\n\nPrice $999.9\n\nPorsche Model 928\n\nModel Year 1994\n\nPrice $2112.12\n\nAudi Model A5\n\nModel Year 2012\n\nPrice $2455.81\n\nSubaru Model Impreza\n\nModel Year 2006\n\nPrice $2437.81\n\nMitsubishi Model Montero\n\nModel Year 1996\n\nPrice $3217.31\n\nToyota Model Matrix\n\nModel Year 2005\n\nPrice $1238.19\n\nSaturn Model VUE\n\nModel Year 2006\n\nPrice $3042.96\n\nVolkswagen Model Passat\n\nModel Year 2008\n\nPrice $1731.98\n\nMitsubishi Model Montero\n\nModel Year 2002\n\nPrice $2814.46',
        time: 1626641697965,
        pageUrl: 'http://localhost:3002/cars-board',
      },
      {
        element: 'button',
        action: 'mouseover',
        dataHook: 'button-cars-board',
        x: 181,
        y: 119,
        value: 'ADD NEW CAR',
        time: 1626641697990,
        pageUrl: 'http://localhost:3002/cars-board',
      },
      {
        element: 'button',
        action: 'mouseover',
        dataHook: 'button-cars-board',
        x: 175,
        y: 113,
        value: 'ADD NEW CAR',
        time: 1626641698025,
        pageUrl: 'http://localhost:3002/cars-board',
      },
      {
        element: 'button',
        action: 'mousedown',
        dataHook: 'button-cars-board',
        x: 168,
        y: 107,
        value: 'ADD NEW CAR',
        time: 1626641698114,
        pageUrl: 'http://localhost:3002/cars-board',
      },
      {
        element: 'button',
        action: 'mouseup',
        dataHook: 'button-cars-board',
        x: 168,
        y: 107,
        value: 'ADD NEW CAR',
        time: 1626641698227,
        pageUrl: 'http://localhost:3002/cars-board',
      },
      {
        element: 'button',
        action: 'click',
        dataHook: 'button-cars-board',
        x: 168,
        y: 107,
        value: 'ADD NEW CAR',
        time: 1626641698286,
        pageUrl: 'http://localhost:3002/cars-board',
      },
      {
        element: 'form',
        action: 'mouseover',
        dataHook: 'car-form',
        x: 168,
        y: 107,
        value:
          'Close window\nBrand Name *\nModel *\nModel Year *\nPrice *\nColor *\nImage URL\nSUBMIT',
        time: 1626641698288,
        pageUrl: 'http://localhost:3002/cars-board',
      },
      {
        element: 'form',
        action: 'mouseover',
        dataHook: 'car-form',
        x: 260,
        y: 136,
        value:
          'Close window\nBrand Name *\nModel *\nModel Year *\nPrice *\nColor *\nImage URL\nSUBMIT',
        time: 1626641699597,
        pageUrl: 'http://localhost:3002/cars-board',
      },
      {
        element: 'input',
        action: 'mouseover',
        dataHook: 'brand-name',
        x: 254,
        y: 151,
        value: '',
        time: 1626641699644,
        pageUrl: 'http://localhost:3002/cars-board',
      },
      {
        element: 'input',
        action: 'mousedown',
        dataHook: 'brand-name',
        x: 221,
        y: 167,
        value: '',
        time: 1626641699813,
        pageUrl: 'http://localhost:3002/cars-board',
      },
      {
        element: 'input',
        action: 'mouseup',
        dataHook: 'brand-name',
        x: 221,
        y: 167,
        value: '',
        time: 1626641699925,
        pageUrl: 'http://localhost:3002/cars-board',
      },
      {
        element: 'input',
        action: 'click',
        dataHook: 'brand-name',
        x: 221,
        y: 167,
        value: '',
        time: 1626641699926,
        pageUrl: 'http://localhost:3002/cars-board',
      },
      {
        element: 'input',
        action: 'change',
        dataHook: 'brand-name',
        x: 0,
        y: 0,
        value: 'BMW',
        time: 1626641701133,
        pageUrl: 'http://localhost:3002/cars-board',
      },
      {
        element: 'input',
        action: 'mouseover',
        dataHook: 'car-model',
        x: 142,
        y: 201,
        value: '',
        time: 1626641701135,
        pageUrl: 'http://localhost:3002/cars-board',
      },
      {
        element: 'input',
        action: 'mousedown',
        dataHook: 'car-model',
        x: 142,
        y: 213,
        value: '',
        time: 1626641701478,
        pageUrl: 'http://localhost:3002/cars-board',
      },
      {
        element: 'input',
        action: 'mouseup',
        dataHook: 'car-model',
        x: 142,
        y: 213,
        value: '',
        time: 1626641701558,
        pageUrl: 'http://localhost:3002/cars-board',
      },
      {
        element: 'input',
        action: 'click',
        dataHook: 'car-model',
        x: 142,
        y: 213,
        value: '',
        time: 1626641701559,
        pageUrl: 'http://localhost:3002/cars-board',
      },
      {
        element: 'input',
        action: 'change',
        dataHook: 'car-model',
        x: 0,
        y: 0,
        value: 'I8',
        time: 1626641702061,
        pageUrl: 'http://localhost:3002/cars-board',
      },
      {
        element: 'input',
        action: 'mouseover',
        dataHook: 'car-model-year',
        x: 124,
        y: 251,
        value: '',
        time: 1626641702064,
        pageUrl: 'http://localhost:3002/cars-board',
      },
      {
        element: 'input',
        action: 'mousedown',
        dataHook: 'car-model-year',
        x: 130,
        y: 265,
        value: '',
        time: 1626641702412,
        pageUrl: 'http://localhost:3002/cars-board',
      },
      {
        element: 'input',
        action: 'mouseup',
        dataHook: 'car-model-year',
        x: 130,
        y: 265,
        value: '',
        time: 1626641702491,
        pageUrl: 'http://localhost:3002/cars-board',
      },
      {
        element: 'input',
        action: 'click',
        dataHook: 'car-model-year',
        x: 130,
        y: 265,
        value: '',
        time: 1626641702492,
        pageUrl: 'http://localhost:3002/cars-board',
      },
      {
        element: 'form',
        action: 'mouseover',
        dataHook: 'car-form',
        x: 128,
        y: 280,
        value:
          'Close window\nBrand Name *\nModel *\nModel Year *\nPrice *\nColor *\nImage URL\nSUBMIT',
        time: 1626641702763,
        pageUrl: 'http://localhost:3002/cars-board',
      },
      {
        element: 'input',
        action: 'mouseover',
        dataHook: 'price',
        x: 122,
        y: 299,
        value: '',
        time: 1626641705077,
        pageUrl: 'http://localhost:3002/cars-board',
      },
      {
        element: 'input',
        action: 'mousedown',
        dataHook: 'price',
        x: 111,
        y: 325,
        value: '',
        time: 1626641705336,
        pageUrl: 'http://localhost:3002/cars-board',
      },
      {
        element: 'input',
        action: 'change',
        dataHook: 'car-model-year',
        x: 0,
        y: 0,
        value: '2019',
        time: 1626641705337,
        pageUrl: 'http://localhost:3002/cars-board',
      },
      {
        element: 'input',
        action: 'mouseup',
        dataHook: 'price',
        x: 111,
        y: 325,
        value: '',
        time: 1626641705413,
        pageUrl: 'http://localhost:3002/cars-board',
      },
      {
        element: 'input',
        action: 'click',
        dataHook: 'price',
        x: 111,
        y: 325,
        value: '',
        time: 1626641705415,
        pageUrl: 'http://localhost:3002/cars-board',
      },
      {
        element: 'form',
        action: 'mouseover',
        dataHook: 'car-form',
        x: 117,
        y: 326,
        value:
          'Close window\nBrand Name *\nModel *\nModel Year *\nPrice *\nColor *\nImage URL\nSUBMIT',
        time: 1626641705654,
        pageUrl: 'http://localhost:3002/cars-board',
      },
      {
        element: 'input',
        action: 'mouseover',
        dataHook: 'car-color',
        x: 128,
        y: 345,
        value: '',
        time: 1626641707421,
        pageUrl: 'http://localhost:3002/cars-board',
      },
      {
        element: 'form',
        action: 'mouseover',
        dataHook: 'car-form',
        x: 128,
        y: 382,
        value:
          'Close window\nBrand Name *\nModel *\nModel Year *\nPrice *\nColor *\nImage URL\nSUBMIT',
        time: 1626641707449,
        pageUrl: 'http://localhost:3002/cars-board',
      },
      {
        element: 'input',
        action: 'mouseover',
        dataHook: 'car-img',
        x: 126,
        y: 391,
        value: '',
        time: 1626641707461,
        pageUrl: 'http://localhost:3002/cars-board',
      },
      {
        element: 'form',
        action: 'mouseover',
        dataHook: 'car-form',
        x: 106,
        y: 386,
        value:
          'Close window\nBrand Name *\nModel *\nModel Year *\nPrice *\nColor *\nImage URL\nSUBMIT',
        time: 1626641707659,
        pageUrl: 'http://localhost:3002/cars-board',
      },
      {
        element: 'input',
        action: 'mouseover',
        dataHook: 'car-color',
        x: 89,
        y: 372,
        value: '',
        time: 1626641707725,
        pageUrl: 'http://localhost:3002/cars-board',
      },
      {
        element: 'input',
        action: 'mousedown',
        dataHook: 'car-color',
        x: 85,
        y: 353,
        value: '',
        time: 1626641707878,
        pageUrl: 'http://localhost:3002/cars-board',
      },
      {
        element: 'input',
        action: 'change',
        dataHook: 'price',
        x: 0,
        y: 0,
        value: '12345',
        time: 1626641707879,
        pageUrl: 'http://localhost:3002/cars-board',
      },
      {
        element: 'input',
        action: 'mouseup',
        dataHook: 'car-color',
        x: 85,
        y: 353,
        value: '',
        time: 1626641707958,
        pageUrl: 'http://localhost:3002/cars-board',
      },
      {
        element: 'input',
        action: 'click',
        dataHook: 'car-color',
        x: 85,
        y: 353,
        value: '',
        time: 1626641707960,
        pageUrl: 'http://localhost:3002/cars-board',
      },
      {
        element: 'input',
        action: 'change',
        dataHook: 'car-color',
        x: 0,
        y: 0,
        value: 'wihte',
        time: 1626641708632,
        pageUrl: 'http://localhost:3002/cars-board',
      },
      {
        element: 'input',
        action: 'mouseover',
        dataHook: 'car-img',
        x: 101,
        y: 393,
        value: '',
        time: 1626641708641,
        pageUrl: 'http://localhost:3002/cars-board',
      },
      {
        element: 'input',
        action: 'mousedown',
        dataHook: 'car-img',
        x: 153,
        y: 404,
        value: '',
        time: 1626641708936,
        pageUrl: 'http://localhost:3002/cars-board',
      },
      {
        element: 'input',
        action: 'mouseup',
        dataHook: 'car-img',
        x: 154,
        y: 404,
        value: '',
        time: 1626641709025,
        pageUrl: 'http://localhost:3002/cars-board',
      },
      {
        element: 'input',
        action: 'click',
        dataHook: 'car-img',
        x: 154,
        y: 404,
        value: '',
        time: 1626641709026,
        pageUrl: 'http://localhost:3002/cars-board',
      },
      {
        element: 'input',
        action: 'change',
        dataHook: 'car-img',
        x: 0,
        y: 0,
        value:
          'https://s.aolcdn.com/commerce/autodata/images/USC90BMC681A021001.jpg',
        time: 1626641709598,
        pageUrl: 'http://localhost:3002/cars-board',
      },
      {
        element: 'form',
        action: 'mouseover',
        dataHook: 'car-form',
        x: 156,
        y: 441,
        value:
          'Close window\nBrand Name *\nModel *\nModel Year *\nPrice *\nColor *\nImage URL\nSUBMIT',
        time: 1626641709608,
        pageUrl: 'http://localhost:3002/cars-board',
      },
      {
        element: 'button',
        action: 'mouseover',
        dataHook: 'car-form-submit-btn',
        x: 377,
        y: 445,
        value: 'SUBMIT',
        time: 1626641709905,
        pageUrl: 'http://localhost:3002/cars-board',
      },
      {
        element: 'button',
        action: 'mouseover',
        dataHook: 'car-form-submit-btn',
        x: 393,
        y: 449,
        value: 'SUBMIT',
        time: 1626641709924,
        pageUrl: 'http://localhost:3002/cars-board',
      },
      {
        element: 'button',
        action: 'mousedown',
        dataHook: 'car-form-submit-btn',
        x: 403,
        y: 451,
        value: 'SUBMIT',
        time: 1626641710154,
        pageUrl: 'http://localhost:3002/cars-board',
      },
      {
        element: 'button',
        action: 'mouseup',
        dataHook: 'car-form-submit-btn',
        x: 403,
        y: 451,
        value: 'SUBMIT',
        time: 1626641710244,
        pageUrl: 'http://localhost:3002/cars-board',
      },
      {
        element: 'button',
        action: 'click',
        dataHook: 'car-form-submit-btn',
        x: 403,
        y: 451,
        value: 'SUBMIT',
        time: 1626641710245,
        pageUrl: 'http://localhost:3002/cars-board',
      },
      {
        element: 'form',
        action: 'mouseover',
        dataHook: 'car-form',
        x: 403,
        y: 451,
        value:
          'Close window\nBrand Name *\nModel *\nModel Year *\nPrice *\nColor *\nImage URL\nLOADING . . .',
        time: 1626641710274,
        pageUrl: 'http://localhost:3002/cars-board',
      },
      {
        element: 'button',
        action: 'mouseover',
        dataHook: 'button-FILTER',
        x: 403,
        y: 451,
        value: 'FILTER',
        time: 1626641710629,
        pageUrl: 'http://localhost:3002/cars-board',
      },
      {
        element: 'button',
        action: 'mouseover',
        dataHook: 'button-display-all',
        x: 422,
        y: 456,
        value: 'DISPLAY ALL',
        time: 1626641712120,
        pageUrl: 'http://localhost:3002/cars-board',
      },
      {
        element: 'button',
        action: 'mouseover',
        dataHook: 'button-display-all',
        x: 446,
        y: 474,
        value: 'DISPLAY ALL',
        time: 1626641712141,
        pageUrl: 'http://localhost:3002/cars-board',
      },
      {
        element: 'div',
        action: 'mouseover',
        dataHook: 'car-card',
        x: 659,
        y: 757,
        value:
          'BMW Model I8\n\nModel Year 2019\n\nPrice $12345\n\nEDIT CAR\nDELETE',
        time: 1626641712235,
        pageUrl: 'http://localhost:3002/cars-board',
      },
      {
        element: 'div',
        action: 'mouseover',
        dataHook: 'car-card',
        x: 675,
        y: 788,
        value:
          'BMW Model I8\n\nModel Year 2019\n\nPrice $12345\n\nEDIT CAR\nDELETE',
        time: 1626641712254,
        pageUrl: 'http://localhost:3002/cars-board',
      },
      {
        element: 'div',
        action: 'mouseover',
        dataHook: 'car-card',
        x: 681,
        y: 801,
        value: 'Mazda Model 323\n\nModel Year 2010\n\nPrice $3000',
        time: 1626641712270,
        pageUrl: 'http://localhost:3002/cars-board',
      },
      {
        element: 'div',
        action: 'mouseover',
        dataHook: 'car-card',
        x: 685,
        y: 808,
        value: 'Mazda Model 323\n\nModel Year 2010\n\nPrice $3000',
        time: 1626641712276,
        pageUrl: 'http://localhost:3002/cars-board',
      },
      {
        element: 'div',
        action: 'mouseover',
        dataHook: 'car-card',
        x: 701,
        y: 830,
        value: 'Mazda Model 323\n\nModel Year 2010\n\nPrice $3000',
        time: 1626641712492,
        pageUrl: 'http://localhost:3002/cars-board',
      },
      {
        element: 'div',
        action: 'mouseover',
        dataHook: 'car-card',
        x: 728,
        y: 858,
        value: 'Mazda Model 323\n\nModel Year 2010\n\nPrice $3000',
        time: 1626641712524,
        pageUrl: 'http://localhost:3002/cars-board',
      },
    ],
  };
};

(async function() {
  const { pageUrl = '', tests = [], height, width } = await getTestJson();
  const browser = await puppeteer.launch({
    headless: true,
    // slowMo: 70,
    args: [
      '--no-sandbox', // I needed these args for it to run on my machine, you probably don't need them.
      '--disable-setuid-sandbox',
      '--window-size=1000,900',
    ],
  });
  try {
    console.log('Start', new Date());
    const page = await browser.newPage();
    await page.setViewport({
      width,
      height,
    });
    await forLoop(tests, page, pageUrl);
    await browser.close();
    console.log('End', new Date());
  } catch (err) {
    console.log(err);
  }
})();

const forLoop = async (tests, page) => {
  for (let index = 0; index < tests.length; index++) {
    const test = tests[index];
    const nextTest = tests[index] || null;

    if (nextTest) {
      console.time('start waiting ...');
      const timeToWait =
        new Date(nextTest.time - test.time).getSeconds() * 1000;
      await delay(timeToWait);
      console.timeEnd('start waiting ...');
    }

    if (index === 0) {
      await page.goto(test.pageUrl, { waitUntil: 'networkidle0' });
    }
    const data = { page, ...test };
    await generateTestAction({ ...data });
  }
};

export const delay = (ms) => {
  return new Promise((resolve, reject) => {
    setTimeout(resolve, ms);
  });
};
