export const testObject = {
	tests: [
		{
			pageUrl: 'https://danieladmaso.github.io/books-project/',
			element: 'a',
			time: 1627762764447,
			value: 'Collections',
			action: 'mousedown',
		},
		{
			pageUrl: 'https://danieladmaso.github.io/books-project/',
			element: 'a',
			time: 1627762764536,
			value: 'Collections',
			action: 'mouseup',
		},
		{
			pageUrl: 'https://danieladmaso.github.io/books-project/collections',
			element: 'a',
			time: 1627762764544,
			value: 'Collections',
			action: 'click',
		},
		{
			x: 298,
			y: 103,
			pageUrl: 'https://danieladmaso.github.io/books-project/collections',
			element: 'input',
			time: 1627762764933,
			dataHook: 'add-collection-input',
			value: '',
			action: 'mouseover',
		},
		{
			x: 256,
			y: 117,
			pageUrl: 'https://danieladmaso.github.io/books-project/collections',
			element: 'input',
			time: 1627762765267,
			dataHook: 'add-collection-input',
			value: '',
			action: 'mousedown',
		},
		{
			x: 255,
			y: 117,
			pageUrl: 'https://danieladmaso.github.io/books-project/collections',
			element: 'input',
			time: 1627762765367,
			dataHook: 'add-collection-input',
			value: '',
			action: 'mouseup',
		},
		{
			x: 255,
			y: 117,
			pageUrl: 'https://danieladmaso.github.io/books-project/collections',
			element: 'input',
			time: 1627762765368,
			dataHook: 'add-collection-input',
			value: '',
			action: 'click',
		},
		{
			x: 347,
			y: 116,
			pageUrl: 'https://danieladmaso.github.io/books-project/collections',
			element: 'svg',
			time: 1627762767021,
			dataHook: 'add-collection-icon',
			action: 'mouseover',
		},
		{
			x: 351,
			y: 115,
			pageUrl: 'https://danieladmaso.github.io/books-project/collections',
			element: 'svg',
			time: 1627762767067,
			dataHook: 'add-collection-icon',
			action: 'mousedown',
		},
		{
			x: 0,
			y: 0,
			pageUrl: 'https://danieladmaso.github.io/books-project/collections',
			element: 'input',
			time: 1627762767067,
			dataHook: 'add-collection-input',
			value: 'dsa',
			action: 'change',
		},
		{
			x: 352,
			y: 115,
			pageUrl: 'https://danieladmaso.github.io/books-project/collections',
			element: 'svg',
			time: 1627762767156,
			dataHook: 'add-collection-icon',
			action: 'mouseup',
		},
		{
			x: 352,
			y: 115,
			pageUrl: 'https://danieladmaso.github.io/books-project/collections',
			element: 'svg',
			time: 1627762767161,
			dataHook: 'add-collection-icon',
			action: 'click',
		},
		{
			x: 336,
			y: 115,
			pageUrl: 'https://danieladmaso.github.io/books-project/collections',
			element: 'input',
			time: 1627762767410,
			dataHook: 'add-collection-input',
			value: '',
			action: 'mouseover',
		},
		{
			x: 245,
			y: 120,
			pageUrl: 'https://danieladmaso.github.io/books-project/collections',
			element: 'input',
			time: 1627762767711,
			dataHook: 'add-collection-input',
			value: '',
			action: 'mousedown',
		},
		{
			x: 245,
			y: 120,
			pageUrl: 'https://danieladmaso.github.io/books-project/collections',
			element: 'input',
			time: 1627762767811,
			dataHook: 'add-collection-input',
			value: '',
			action: 'mouseup',
		},
		{
			x: 245,
			y: 120,
			pageUrl: 'https://danieladmaso.github.io/books-project/collections',
			element: 'input',
			time: 1627762767812,
			dataHook: 'add-collection-input',
			value: '',
			action: 'click',
		},
		{
			x: 354,
			y: 113,
			pageUrl: 'https://danieladmaso.github.io/books-project/collections',
			element: 'svg',
			time: 1627762769172,
			dataHook: 'add-collection-icon',
			action: 'mouseover',
		},
		{
			x: 355,
			y: 113,
			pageUrl: 'https://danieladmaso.github.io/books-project/collections',
			element: 'svg',
			time: 1627762769272,
			dataHook: 'add-collection-icon',
			action: 'mousedown',
		},
		{
			x: 0,
			y: 0,
			pageUrl: 'https://danieladmaso.github.io/books-project/collections',
			element: 'input',
			time: 1627762769273,
			dataHook: 'add-collection-input',
			value: 'sad',
			action: 'change',
		},
		{
			x: 355,
			y: 113,
			pageUrl: 'https://danieladmaso.github.io/books-project/collections',
			element: 'svg',
			time: 1627762769361,
			dataHook: 'add-collection-icon',
			action: 'mouseup',
		},
		{
			x: 355,
			y: 113,
			pageUrl: 'https://danieladmaso.github.io/books-project/collections',
			element: 'svg',
			time: 1627762769364,
			dataHook: 'add-collection-icon',
			action: 'click',
		},
		{
			x: 347,
			y: 108,
			pageUrl: 'https://danieladmaso.github.io/books-project/collections',
			element: 'svg',
			time: 1627762769827,
			dataHook: 'add-collection-icon',
			action: 'mouseover',
		},
		{
			pageUrl: 'https://danieladmaso.github.io/books-project/collections',
			element: 'a',
			time: 1627762770214,
			value: 'Search Books',
			action: 'mousedown',
		},
		{
			pageUrl: 'https://danieladmaso.github.io/books-project/collections',
			element: 'a',
			time: 1627762770320,
			value: 'Search Books',
			action: 'mouseup',
		},
		{
			pageUrl: 'https://danieladmaso.github.io/books-project/search',
			element: 'a',
			time: 1627762770323,
			value: 'Search Books',
			action: 'click',
		},
		{
			x: 479,
			y: 186,
			pageUrl: 'https://danieladmaso.github.io/books-project/search',
			element: 'input',
			time: 1627762771296,
			dataHook: 'search-input',
			value: '',
			action: 'mouseover',
		},
		{
			x: 479,
			y: 183,
			pageUrl: 'https://danieladmaso.github.io/books-project/search',
			element: 'input',
			time: 1627762771353,
			dataHook: 'search-input',
			value: '',
			action: 'mousedown',
		},
		{
			x: 479,
			y: 183,
			pageUrl: 'https://danieladmaso.github.io/books-project/search',
			element: 'input',
			time: 1627762771455,
			dataHook: 'search-input',
			value: '',
			action: 'mouseup',
		},
		{
			x: 479,
			y: 183,
			pageUrl: 'https://danieladmaso.github.io/books-project/search',
			element: 'input',
			time: 1627762771455,
			dataHook: 'search-input',
			value: '',
			action: 'click',
		},
		{
			x: 0,
			y: 0,
			pageUrl: 'https://danieladmaso.github.io/books-project/search',
			element: 'input',
			time: 1627762773118,
			dataHook: 'search-input',
			value: 'dbz',
			action: 'change',
		},
		{
			x: 520,
			y: 423,
			pageUrl: 'https://danieladmaso.github.io/books-project/search',
			element: 'div',
			time: 1627762775982,
			dataHook: 'all-books',
			value:
				'DBZ Battle Boardgame\n\nLicensed\n\n2003\n\nComposition Notebook\n\nStephan Werfel\n\n2020\n\nComposition Notebook : DBZ Son Goku Dragon Ball Super Z Soft Glossy Cover College Ruled Lined Pages Book for Boys 6 X 9 Inches 100 Pages\n\nRay Kon\n\n2020\n\nComposition Notebook : DBZ Son Goku Dragon Ball Super Z Soft Glossy Cover College Ruled Lined Pages Book for Boys 6 X 9 Inches 110 Pages\n\nRay Kon\n\n2020\n\nUthingo lwenkosazana\n\nD.B.Z. Ntuli\n\n1978\n\nKuyosala izibongo\n\nJ. C. Dlamini\n\n2003\n\nUgqozi\n\nD.B.Z. Ntuli\n\n2004\n\nIthemba\n\nD.B.Z. Ntuli\n\n2004\n\nIshashalazi\n\nN. F. Mbhele\n\n1988\n\nIngcamu\n\n1989\n\nYihlathi Leli\n\nB. D. Khawula\n\n2012\n\nIdubukele\n\n1987\n\nIzimpande\n\nD.B.Z. NtuliM. Makhambeni\n\nImicibisholo\n\nD. B. Z. Ntuli\n\n1970\n\nImilando YakwaZulu (Zulu History)\n\nHubert Sishi\n\n2000\n\nIzimpande\n\nD.B.Z. NtuliMn Makhambeni\n\n1998\n\nMetal Architecture\n\nBurkhard Frohlich\n\n2003\n\nIzikhwili, izindatshana\n\nD. B. Z. Ntuli\n\n1972\n\nColoring Book and Poster Collection\n\nDragonzy ColoringDragonzy Coloring\n\n2019\n\nNgamafuphi\n\nD. B. Z. Ntuli\n\n1985\n\nLalela-ke\n\nD. B. Z. Ntuli\n\n1991\n\nIndoni yamanzi\n\nD. B. Z. Ntuli\n\n1992\n\nThe poetry of B.W. Vilakazi\n\nD. B. Z. Ntuli\n\n1984\n\nArchitektur-Details\n\n1958\n\nInduku\n\nD. B. Z. Ntuli\n\n1992\n\nImidlalo kaZakes Mda\n\nZakes Mda\n\n2002\n\nThe rainbow flute\n\nModison Salayedvwa MagagulaD. B. Z. Ntuli\n\n1997',
			action: 'mouseover',
		},
		{
			x: 522,
			y: 431,
			pageUrl: 'https://danieladmaso.github.io/books-project/search',
			element: 'div',
			time: 1627762775991,
			dataHook: 'book-2',
			value: '',
			action: 'mouseover',
		},
		{
			x: 509,
			y: 567,
			pageUrl: 'https://danieladmaso.github.io/books-project/search',
			element: 'svg',
			time: 1627762776506,
			dataHook: 'imageIcon-book-2',
			action: 'mouseover',
		},
		{
			x: 513,
			y: 581,
			pageUrl: 'https://danieladmaso.github.io/books-project/search',
			element: 'svg',
			time: 1627762776880,
			dataHook: 'imageIcon-book-2',
			action: 'mousedown',
		},
		{
			x: 513,
			y: 581,
			pageUrl: 'https://danieladmaso.github.io/books-project/search',
			element: 'svg',
			time: 1627762776955,
			dataHook: 'imageIcon-book-2',
			action: 'mouseup',
		},
		{
			x: 513,
			y: 581,
			pageUrl: 'https://danieladmaso.github.io/books-project/search',
			element: 'svg',
			time: 1627762776958,
			dataHook: 'imageIcon-book-2',
			action: 'click',
		},
		{
			x: 513,
			y: 581,
			pageUrl: 'https://danieladmaso.github.io/books-project/search',
			element: 'select',
			id: '',
			time: 1627762776959,
			dataHook: 'select-book-2',
			value: 'select collection',
			action: 'mouseover',
		},
		{
			x: 508,
			y: 600,
			pageUrl: 'https://danieladmaso.github.io/books-project/search',
			element: 'div',
			time: 1627762777248,
			dataHook: 'book-2',
			value: 'select collection\ndsa\nsad',
			action: 'mouseover',
		},
		{
			x: 507,
			y: 602,
			pageUrl: 'https://danieladmaso.github.io/books-project/search',
			element: 'div',
			time: 1627762777496,
			dataHook: 'book-2',
			value: 'select collection\ndsa\nsad',
			action: 'mousedown',
		},
		{
			x: 507,
			y: 602,
			pageUrl: 'https://danieladmaso.github.io/books-project/search',
			element: 'div',
			time: 1627762777583,
			dataHook: 'book-2',
			value: 'select collection\ndsa\nsad',
			action: 'mouseup',
		},
		{
			x: 507,
			y: 602,
			pageUrl: 'https://danieladmaso.github.io/books-project/search',
			element: 'div',
			time: 1627762777583,
			dataHook: 'book-2',
			value: 'select collection\ndsa\nsad',
			action: 'click',
		},
		{
			x: 507,
			y: 598,
			pageUrl: 'https://danieladmaso.github.io/books-project/search',
			element: 'select',
			id: '',
			time: 1627762777888,
			dataHook: 'select-book-2',
			value: 'select collection',
			action: 'mouseover',
		},
		{
			x: 506,
			y: 596,
			pageUrl: 'https://danieladmaso.github.io/books-project/search',
			element: 'select',
			id: '',
			time: 1627762777935,
			dataHook: 'select-book-2',
			value: 'select collection',
			action: 'mousedown',
		},
		{
			x: 506,
			y: 596,
			pageUrl: 'https://danieladmaso.github.io/books-project/search',
			element: 'select',
			id: '',
			time: 1627762777937,
			dataHook: 'select-book-2',
			value: 'select collection',
			action: 'mouseup',
		},
		{
			x: 506,
			y: 596,
			pageUrl: 'https://danieladmaso.github.io/books-project/search',
			element: 'select',
			id: '',
			time: 1627762777937,
			dataHook: 'select-book-2',
			value: 'select collection',
			action: 'click',
		},
		{
			x: 0,
			y: 0,
			pageUrl: 'https://danieladmaso.github.io/books-project/search',
			element: 'select',
			id: '',
			time: 1627762779155,
			dataHook: 'select-book-2',
			value: 'sad',
			action: 'change',
		},
		{
			x: 506,
			y: 596,
			pageUrl: 'https://danieladmaso.github.io/books-project/search',
			element: 'div',
			time: 1627762779156,
			dataHook: 'book-2',
			value: '',
			action: 'mouseover',
		},
		{
			x: 728,
			y: 597,
			pageUrl: 'https://danieladmaso.github.io/books-project/search',
			element: 'div',
			time: 1627762779229,
			dataHook: 'book-3',
			value: '',
			action: 'mouseover',
		},
		{
			x: 720,
			y: 585,
			pageUrl: 'https://danieladmaso.github.io/books-project/search',
			element: 'svg',
			time: 1627762779346,
			dataHook: 'imageIcon-book-3',
			action: 'mouseover',
		},
		{
			x: 711,
			y: 578,
			pageUrl: 'https://danieladmaso.github.io/books-project/search',
			element: 'svg',
			time: 1627762779669,
			dataHook: 'imageIcon-book-3',
			action: 'mousedown',
		},
		{
			x: 711,
			y: 578,
			pageUrl: 'https://danieladmaso.github.io/books-project/search',
			element: 'svg',
			time: 1627762779736,
			dataHook: 'imageIcon-book-3',
			action: 'mouseup',
		},
		{
			x: 711,
			y: 578,
			pageUrl: 'https://danieladmaso.github.io/books-project/search',
			element: 'svg',
			time: 1627762779738,
			dataHook: 'imageIcon-book-3',
			action: 'click',
		},
		{
			x: 711,
			y: 578,
			pageUrl: 'https://danieladmaso.github.io/books-project/search',
			element: 'div',
			time: 1627762779749,
			dataHook: 'book-3',
			value: 'select collection\ndsa\nsad',
			action: 'mouseover',
		},
		{
			x: 710,
			y: 581,
			pageUrl: 'https://danieladmaso.github.io/books-project/search',
			element: 'select',
			id: '',
			time: 1627762779938,
			dataHook: 'select-book-3',
			value: 'select collection',
			action: 'mouseover',
		},
		{
			x: 702,
			y: 599,
			pageUrl: 'https://danieladmaso.github.io/books-project/search',
			element: 'div',
			time: 1627762780060,
			dataHook: 'book-3',
			value: 'select collection\ndsa\nsad',
			action: 'mouseover',
		},
		{
			x: 701,
			y: 600,
			pageUrl: 'https://danieladmaso.github.io/books-project/search',
			element: 'div',
			time: 1627762780162,
			dataHook: 'book-3',
			value: 'select collection\ndsa\nsad',
			action: 'mousedown',
		},
		{
			x: 701,
			y: 600,
			pageUrl: 'https://danieladmaso.github.io/books-project/search',
			element: 'div',
			time: 1627762780229,
			dataHook: 'book-3',
			value: 'select collection\ndsa\nsad',
			action: 'mouseup',
		},
		{
			x: 701,
			y: 600,
			pageUrl: 'https://danieladmaso.github.io/books-project/search',
			element: 'div',
			time: 1627762780230,
			dataHook: 'book-3',
			value: 'select collection\ndsa\nsad',
			action: 'click',
		},
		{
			x: 701,
			y: 598,
			pageUrl: 'https://danieladmaso.github.io/books-project/search',
			element: 'select',
			id: '',
			time: 1627762780572,
			dataHook: 'select-book-3',
			value: 'select collection',
			action: 'mouseover',
		},
		{
			x: 700,
			y: 596,
			pageUrl: 'https://danieladmaso.github.io/books-project/search',
			element: 'select',
			id: '',
			time: 1627762780624,
			dataHook: 'select-book-3',
			value: 'select collection',
			action: 'mousedown',
		},
		{
			x: 700,
			y: 596,
			pageUrl: 'https://danieladmaso.github.io/books-project/search',
			element: 'select',
			id: '',
			time: 1627762780626,
			dataHook: 'select-book-3',
			value: 'select collection',
			action: 'mouseup',
		},
		{
			x: 700,
			y: 596,
			pageUrl: 'https://danieladmaso.github.io/books-project/search',
			element: 'select',
			id: '',
			time: 1627762780626,
			dataHook: 'select-book-3',
			value: 'select collection',
			action: 'click',
		},
		{
			x: 0,
			y: 0,
			pageUrl: 'https://danieladmaso.github.io/books-project/search',
			element: 'select',
			id: '',
			time: 1627762781795,
			dataHook: 'select-book-3',
			value: 'sad',
			action: 'change',
		},
		{
			x: 700,
			y: 596,
			pageUrl: 'https://danieladmaso.github.io/books-project/search',
			element: 'div',
			time: 1627762781801,
			dataHook: 'book-3',
			value: '',
			action: 'mouseover',
		},
		{
			x: 793,
			y: 646,
			pageUrl: 'https://danieladmaso.github.io/books-project/search',
			element: 'div',
			time: 1627762782133,
			dataHook: 'all-books',
			value:
				'DBZ Battle Boardgame\n\nLicensed\n\n2003\n\nComposition Notebook\n\nStephan Werfel\n\n2020\n\nComposition Notebook : DBZ Son Goku Dragon Ball Super Z Soft Glossy Cover College Ruled Lined Pages Book for Boys 6 X 9 Inches 100 Pages\n\nRay Kon\n\n2020\n\nComposition Notebook : DBZ Son Goku Dragon Ball Super Z Soft Glossy Cover College Ruled Lined Pages Book for Boys 6 X 9 Inches 110 Pages\n\nRay Kon\n\n2020\n\nUthingo lwenkosazana\n\nD.B.Z. Ntuli\n\n1978\n\nKuyosala izibongo\n\nJ. C. Dlamini\n\n2003\n\nUgqozi\n\nD.B.Z. Ntuli\n\n2004\n\nIthemba\n\nD.B.Z. Ntuli\n\n2004\n\nIshashalazi\n\nN. F. Mbhele\n\n1988\n\nIngcamu\n\n1989\n\nYihlathi Leli\n\nB. D. Khawula\n\n2012\n\nIdubukele\n\n1987\n\nIzimpande\n\nD.B.Z. NtuliM. Makhambeni\n\nImicibisholo\n\nD. B. Z. Ntuli\n\n1970\n\nImilando YakwaZulu (Zulu History)\n\nHubert Sishi\n\n2000\n\nIzimpande\n\nD.B.Z. NtuliMn Makhambeni\n\n1998\n\nMetal Architecture\n\nBurkhard Frohlich\n\n2003\n\nIzikhwili, izindatshana\n\nD. B. Z. Ntuli\n\n1972\n\nColoring Book and Poster Collection\n\nDragonzy ColoringDragonzy Coloring\n\n2019\n\nNgamafuphi\n\nD. B. Z. Ntuli\n\n1985\n\nLalela-ke\n\nD. B. Z. Ntuli\n\n1991\n\nIndoni yamanzi\n\nD. B. Z. Ntuli\n\n1992\n\nThe poetry of B.W. Vilakazi\n\nD. B. Z. Ntuli\n\n1984\n\nArchitektur-Details\n\n1958\n\nInduku\n\nD. B. Z. Ntuli\n\n1992\n\nImidlalo kaZakes Mda\n\nZakes Mda\n\n2002\n\nThe rainbow flute\n\nModison Salayedvwa MagagulaD. B. Z. Ntuli\n\n1997',
			action: 'mouseover',
		},
		{
			x: 908,
			y: 701,
			pageUrl: 'https://danieladmaso.github.io/books-project/search',
			element: 'div',
			time: 1627762782178,
			dataHook: 'book-4',
			value: '',
			action: 'mouseover',
		},
		{
			x: 1018,
			y: 825,
			pageUrl: 'https://danieladmaso.github.io/books-project/search',
			element: 'div',
			time: 1627762782255,
			dataHook: 'all-books',
			value:
				'DBZ Battle Boardgame\n\nLicensed\n\n2003\n\nComposition Notebook\n\nStephan Werfel\n\n2020\n\nComposition Notebook : DBZ Son Goku Dragon Ball Super Z Soft Glossy Cover College Ruled Lined Pages Book for Boys 6 X 9 Inches 100 Pages\n\nRay Kon\n\n2020\n\nComposition Notebook : DBZ Son Goku Dragon Ball Super Z Soft Glossy Cover College Ruled Lined Pages Book for Boys 6 X 9 Inches 110 Pages\n\nRay Kon\n\n2020\n\nUthingo lwenkosazana\n\nD.B.Z. Ntuli\n\n1978\n\nKuyosala izibongo\n\nJ. C. Dlamini\n\n2003\n\nUgqozi\n\nD.B.Z. Ntuli\n\n2004\n\nIthemba\n\nD.B.Z. Ntuli\n\n2004\n\nIshashalazi\n\nN. F. Mbhele\n\n1988\n\nIngcamu\n\n1989\n\nYihlathi Leli\n\nB. D. Khawula\n\n2012\n\nIdubukele\n\n1987\n\nIzimpande\n\nD.B.Z. NtuliM. Makhambeni\n\nImicibisholo\n\nD. B. Z. Ntuli\n\n1970\n\nImilando YakwaZulu (Zulu History)\n\nHubert Sishi\n\n2000\n\nIzimpande\n\nD.B.Z. NtuliMn Makhambeni\n\n1998\n\nMetal Architecture\n\nBurkhard Frohlich\n\n2003\n\nIzikhwili, izindatshana\n\nD. B. Z. Ntuli\n\n1972\n\nColoring Book and Poster Collection\n\nDragonzy ColoringDragonzy Coloring\n\n2019\n\nNgamafuphi\n\nD. B. Z. Ntuli\n\n1985\n\nLalela-ke\n\nD. B. Z. Ntuli\n\n1991\n\nIndoni yamanzi\n\nD. B. Z. Ntuli\n\n1992\n\nThe poetry of B.W. Vilakazi\n\nD. B. Z. Ntuli\n\n1984\n\nArchitektur-Details\n\n1958\n\nInduku\n\nD. B. Z. Ntuli\n\n1992\n\nImidlalo kaZakes Mda\n\nZakes Mda\n\n2002\n\nThe rainbow flute\n\nModison Salayedvwa MagagulaD. B. Z. Ntuli\n\n1997',
			action: 'mouseover',
		},
	],
	width: 1200,
	height: 1095,
};
